[package]
name = "ai_iter_utils"
version = "0.1.0"
edition = "2021"
description = "A short description of my package"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]
bench = false

[dependencies]
